using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Parallax : MonoBehaviour
{
    [SerializeField, Range(0f, 1f)] 
    private float parllaxMultiplier = 0f;

    private Transform cameraTransform;

    private Vector3 lastCameraPosition;

    private void Start()
    {
        cameraTransform = Camera.main.transform;
        lastCameraPosition = cameraTransform.position;
    }

    private void Update()
    {
        Vector3 deltaMovement = cameraTransform.position - lastCameraPosition;
        transform.position += new Vector3(deltaMovement.x * parllaxMultiplier, 0f, 0f);
        lastCameraPosition = cameraTransform.position;
    }
}
